branches:
  only:
  - develop
language: python
install: pip install -r docs/requirements.txt
before_script:
- git config --global user.name "Hoat Le"
- git config --global user.email "hoatlevan@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- cd docs
- make setup_gh_pages
script: make generate
after_script: make deploy
env:
  global:
  - GH_REPO="teracy-official/teracy-dev"
  - secure: PXdIZQP5nCjfA/z22FnNl6zfrqPD8ccO5TRHsYiq53Yqx7dqUGmdcqLohw60IHYm6C2z4Wnkp9fqhDtkQ/eGM0UHcr33mBop0/pOypiPz/utjePFHonTTYNjl9X7+TYHpp1V+TaKtJK4J25lK7GuJUPmNLJD6jvUKcENesh984E=