group: deprecated-2017Q2 # see: https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch
services:
- docker
env:
  matrix:
  - BUILD_TYPE=dev CI_REGISTRY_IMAGE=$DEV_DOCKER_IMAGE
  - BUILD_TYPE=docs CI_REGISTRY_IMAGE=$DOCS_DOCKER_IMAGE
  global:
  - DOCKER_FILE=Dockerfile-dev
  - IMAGE_TAG_PREFIX=dev_
  - CI_BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
before_install:
- git submodule update --init --recursive
install: true
before_script:
- chmod ugo+x ./.travis/build.sh
- chmod ugo+x ./.travis/deploy.sh
- git config --global user.name "Teracy Bot"
- git config --global user.email "teracy.com@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- . ./.travis/setup.sh
- echo $DEPLOY_HTML_DIR
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | sed -e 's/[\/]/-/g' | sed -e 's/[\#]//g'; fi`
- export CONTAINER_IMAGE=$CI_REGISTRY_IMAGE:$IMAGE_TAG_PREFIX$TAG
script:
- ./.travis/build.sh
after_success:
- ./.travis/deploy.sh
notifications:
  slack:
    rooms:
      - secure: 4i1vGAmnysabpirj1LxpVe1QD9/P3Lmf6J8S7qQECwgI+onm7UPDr8V51o6cHC2ptpOCOL/WRpfUuNsiEZnwU+cLx3EbRm0S8/xcJ7uSmqcPh6oHAZ4f32V1tgsTt0g1GHRlGT/nEOw/dg/E+QKHpqEcpAG6fcq4nPNP2Kdixco=
    on_success: change
