branches:
  only:
  - master
  - develop
language: python
install: pip install -r docs/requirements.txt
before_script:
- git config --global user.name "Teracy Bot"
- git config --global user.email "teracy.com@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- . ./.travis/setup.sh
- echo $DEPLOY_HTML_DIR
- cd docs
- make setup_gh_pages
script: make generate
after_script: make deploy
env:
  global:
  - GH_REPO="teracy-official/dev"
  - secure: JNsrd5SEkyzMeNdQsndnfJX+QG/QTLCfqtMkjQWvy6VVwCYXHEZkPu49IirItC8/S2wUoe0BMoaMM+IZEHgAKHHt8UQwwOsagbvh5Fu3LBZvpZ/tC1ewp7IlVrVI/cQ38PC5Y6BaN/rHVPMbs27DQhggMFAw9YCnC8lkGzbfZIM=
