version: "2"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: teracy/dev-docs:dev_develop
    command: bash -c "restview . -l *:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
